@startuml
title = Запрос на подтверждение платежа
actor "Клиент"              as Item1  order 10 
participant "Фронт"              as Item2  order 20 
participant "СОР"              as Item3  order 30 
participant "Сервис платежей"              as Item4  order 40 #00FF00
participant "Сервис генерации подписи"              as Item5  order 50 
participant "Редис"              as Item6  order 60 
  activate Item1 
  activate Item2 
  Item1 -> Item2 : Согласие клиента
  activate Item3 
  Item2 -> Item3 : Запрос на подтверждение платежа\n ID запроса,параметры платежа
  activate Item4 #00FF00
  Item3 -> Item4 : Запрос на подтверждение платежа\n ID запроса,параметры платежа
  activate Item5 
  Item4 -> Item5 : Запрос на подпись
  Item5 -> Item5
  Item5 --> Item4 : Флаг отправки ОТП
  deactivate Item5
  activate Item6 
  Item4 -> Item6 : Сохранение параметров платежа
  Item6 -> Item6
  Item6 --> Item4 : Результат сохранения
  deactivate Item6
  Item4 --> Item3 : Флаг отправки ОТП
  deactivate Item4
  Item3 --> Item2 : Флаг отправки ОТП
  deactivate Item3
  Item2 --> Item1 : Флаг отправки ОТП
  deactivate Item2
  deactivate Item1
@enduml

