@startuml
title = Запрос шага многошагового сценария оплаты
actor "Клиент"              as Item1  order 10 
participant "Фронт"              as Item2  order 20 
participant "СОР"              as Item3  order 30 
participant "Сервис платежей"              as Item4  order 40 #00FF00
participant "AnyWay"              as Item5  order 50 
  activate Item1 
  activate Item2 
  Item1 -> Item2 : Заполнение реквизитов платежа и суммы для каждого шага
  activate Item3 
  Item2 -> Item3 : Запрос на проверку правильности реквизитов \n и расчет комиссии( если FinalStep=true)
  activate Item4 #00FF00
  Item3 -> Item4 : Запрос на проверку правильности реквизитов \n и расчет комиссии( если FinalStep=true)
  activate Item5 
  Item4 -> Item5 : Запрос STEP
  Item5 -> Item5
  Item5 --> Item4 : Возврат ответа
  deactivate Item5
  Item4 --> Item3 : Возврат суммы комиссии ( если FinalStep=true) и \nинформации по полям следующей формы ввода\n(если FinalStep=false) 
  deactivate Item4
  Item3 --> Item2 : Возврат суммы комиссии ( если FinalStep=true) и \nинформации по полям следующей формы ввода\n(если FinalStep=false) 
  deactivate Item3
  Item2 --> Item1 : Возврат суммы комиссии ( если FinalStep=true) и \nочередной формы для заполнения реквизитов\n(если FinalStep=false)
  deactivate Item2
  deactivate Item1
@enduml

