@startuml
title = Совершение платежа в AnyWay с помощью платежного сервиса(блок-схема)
partition "Запрос справочников "{
#lightblue :Запрос справочника провайдеров ANYWAY(AWRPROVIDER)\n <color:red><i>[![GET_Documentation](/img/GET_Documentation.svg)] [[/swagger/index.html#/INFO/getexport описание]]</i>\n [[/Files/export.html диаграмма переходов]] |
detach
note right
  Вызов этих справочников кэшируется [[http://plantuml.com сайте plantuml]]
  и занимает миллисекунды  
  Это следует учитывать
  при проектировании вызовов
end note
#lightgreen :Запрос идентификатора провайдера<

#lightblue :Запрос справочника вендоров ANYWAY(AWREXPORT)\n  <color:red><i> /api/v1/GetVendors</i>|
note right
  Названия методов API 
  приведены ,как пример.
  Будут заполняться
  по мере готовности
end note

}

detach
group Выполнение платежа
partition "Заполнение параметров платежа "{
#lightgreen :Запрос идентификатора провайдера<

if(AWAEXPORT.IsSupportRequestRSTEP = true) then (многоходовый)
  :Выбор  конкретного получателя платежа;
note left
  Детали , в каком случае
  выполняется уточняющий запрос  
  выясним на тестовом полигоне
end note

  #lightgreen :Заполнение секции Search<
#lightblue :Запрос ANYWAY AWRSTEP  Step="0" ,секция Search|
:Назначение currentStep=0;
repeat
#lightgreen :Заполнение реквизитов платежа\n, секция INPUTS предыдущего ответа AWASTEP<
#lightblue :Запрос ANYWAY AWRSTEP  Step=currentStep |
:currentStep=currentStep+1;
repeat while(FinalStep !=true) 

else (одноходовый)
repeat
#lightgreen :Заполнение реквизитов платежа\n, секция ADDITIONAL ( по справочнику вендоров)<
#lightblue :Запрос ANYWAY AWRPUPAY  Check=true|
repeat while(Status!="Executed") 
endif

}
partition "Финализация платежа "{
#lightgreen :Показ финальной формы с уточненной комиссией \n, запрос подтверждения платежа<
#lightblue :Запрос на подтверждение платежа|
repeat
#lightgreen :Экран ввода одноразового пароля \nс основными параметрами платежа<

#lightblue :Запрос подтверждения одноразового пароля.\nВозращается результат проведения платежа|
repeat while(OTP введен правильно?) 
if(Результат платежа) then (Успех)
#lightgreen :Экран сообщения об успешности платеже>
stop
else (Ошибка)
#lightgreen :Экран сообщения об ошибке>
end
endif
}
end group

legend right
    |Цвет| Тип |
    |<#lightgreen>| Действия на фронте|
    |<#lightblue>| Запросы в платежный сервис|
endlegend
@enduml