@startuml
title = Совершение платежа в AnyWay с помощью платежного сервиса(блок-схема)
partition "Запрос справочников "{

#lightblue :Запрос справочника вендоров EXPORT {#export#}|
note right
справочник кэшируется

end note

}

detach
group Выполнение платежа
partition "Заполнение параметров платежа "{
#lightgreen :Запрос идентификатора провайдера<

if(Платеж многоходовый?) then (IsSupportRequestRSTEP=true)
 :Назначение currentStep=1;
repeat
#lightgreen :Заполнение формы с реквизитами платежа<
note left
  В случае , когда Step=1 ,
поля не заполняются,
для следующих шагов набор полей берется 
из секции INPUTS предыдущего ответа STEP
end note

#lightblue :Запрос STEP  Step=currentStep {#step#}|
:currentStep=currentStep+1;
repeat while(FinalStep !=true) 

else (одноходовый)
repeat
#lightgreen :Заполнение реквизитов платежа\n, секция ADDITIONAL ( по справочнику вендоров)<
#lightblue :Запрос PUPAY  Check=true {#pupay#}|
repeat while(Error!=0) 
endif

}
partition "Финализация платежа "{
#lightgreen :Показ финальной формы с уточненной комиссией \n, запрос подтверждения платежа<
#lightblue :Запрос на подтверждение платежа{#requestotp#}|
repeat
#lightgreen :Экран ввода одноразового пароля \nс основными параметрами платежа<

#lightblue :Запрос подтверждения одноразового пароля.\nВозращается результат проведения платежа{#finishpayment#}|
repeat while(OTP введен правильно?) 
if(Результат платежа) then (Успех)
#lightgreen :Экран сообщения об успешности платеже>
stop
else (Ошибка)
#lightgreen :Экран сообщения об ошибке>
end
endif
}
end group

legend right
    |Цвет| Тип |
    |<#lightgreen>| Действия на фронте|
    |<#lightblue>| Запросы в платежный сервис|
endlegend
@enduml